# We need sudo permissions
sudo: required

# tell Travis we need a copy of docker running
services:
  - docker

# Build our image using Dockerfile.dev (?)
before_install:
  # we have to provide a tag name because we don't have an easy way to grab image id
  # given name won't matter too much because it's just an internal name, 
  # but meaninful naming is a best-practice	
  - docker build -t errrzarrr/frontend -f Dockerfile.dev .

# Tell Travis how to run our test suite
# You may want to set the following property if your travis build 
# fails with “rakefile not found” by adding to the top of your .travis.yml file: language: generic 
script:
  - docker run -e CI=true errrzarrr/frontend npm run test -- --coverage


# Tell Travis how to deply our code to AWS
deploy:
  provider: elasticbeanstalk # or DO or hero
  region: "us-east-2"
  app: "fronted_docker"
  env: "FrontedDocker-env"
  bucket_name: "" # in S3 section
  bucket_path: "frontend_docker" # same as app name, usually
  on:
    # deploy only features that were merged into 'master' branch
    branch: master
  access_key_id: "$AWS_PUBLIC_KEY"
  # WARNING: AWS will only show you it once and no more
  secret_access_key:
    secure: "$AWS_PRIVATE_KEY"
